/**
 * 
 * a stub which represents the future mongo storage
 * 
 */
import {Observable} from 'rxjs/Rx';
import {ProductDefaultRoleList} from './productDefaultRoleList';

export class BackendDummy {

  /**
   * a set of default role lists
   * 
   */
  private lists: Array<ProductDefaultRoleList> = new Array<ProductDefaultRoleList>();

  /**
   * 
   * a list for the bronze media production product
   * 
   */
  private mediaBronze: ProductDefaultRoleList = {
    productClass: 'MEDIA',
    applicableProduction: ['BRONZE', 'SILVER', 'GOLD'],
    defaultRoles: [

      /** production office */
      {
        sys_nodedbid: '',
        nvpList_typeName: 'Production manager',
        nvpList_typeDescription: 'Manage the production and ensure delivery on time and to budget',
        nvpList_typeDeliverableType: 'SERVICE',
        nvpList_typeChargeCode: '1010',
        nvpList_typePAYEStatus: 'PAYE',
        nvpList_typeWorkingWeek: 'Six (6) days per week',
        nvpList_typeBudgetMin: 200,
        nvpList_typeBudgetMax: 220,
        nvpList_typeHolidayPaidRate: 200,
        nvpList_typeOvertimePaidRate: 0,
        nvpList_typeNoticePeriod: 0,
        nvpList_typePaymentPeriod: 'Weekly',
        nvpList_typeRatePeriod: 'per day',
        nvpList_typeCurrency: 'GBP',
        nvpList_typeProcessName: 'Contract management process',
        nvpList_typeAdministrationTeam: 'Contracts admin team',
        nvpList_typeContractTemplate: 'e262634a-46c8-48c8-b39d-f288d24af871',
        nvpList_typeCategory: 'Production office'
      },
      {
        sys_nodedbid: '',
        nvpList_typeName: 'Production assistant',
        nvpList_typeDescription: 'Assist the production manager and ensure delivery on time and to budget',
        nvpList_typeDeliverableType: 'SERVICE',
        nvpList_typeChargeCode: '1010',
        nvpList_typePAYEStatus: 'PAYE',
        nvpList_typeWorkingWeek: 'Six (6) days per week',
        nvpList_typeBudgetMin: 180,
        nvpList_typeBudgetMax: 200,
        nvpList_typeHolidayPaidRate: 180,
        nvpList_typeOvertimePaidRate: 0,
        nvpList_typeNoticePeriod: 0,
        nvpList_typePaymentPeriod: 'Weekly',
        nvpList_typeRatePeriod: 'per day',
        nvpList_typeCurrency: 'GBP',
        nvpList_typeProcessName: 'Contract management process',
        nvpList_typeAdministrationTeam: 'Contracts admin team',
        nvpList_typeContractTemplate: 'e262634a-46c8-48c8-b39d-f288d24af871',
        nvpList_typeCategory: 'Production office'
      },
      {
        sys_nodedbid: '',
        nvpList_typeName: 'Producer',
        nvpList_typeDescription: 'Produce the production',
        nvpList_typeDeliverableType: 'SERVICE',
        nvpList_typeChargeCode: '1010',
        nvpList_typePAYEStatus: 'PAYE',
        nvpList_typeWorkingWeek: 'Six (6) days per week',
        nvpList_typeBudgetMin: 300,
        nvpList_typeBudgetMax: 350,
        nvpList_typeHolidayPaidRate: 300,
        nvpList_typeOvertimePaidRate: 0,
        nvpList_typeNoticePeriod: 0,
        nvpList_typePaymentPeriod: 'Weekly',
        nvpList_typeRatePeriod: 'per day',
        nvpList_typeCurrency: 'GBP',
        nvpList_typeProcessName: 'Contract management process',
        nvpList_typeAdministrationTeam: 'Contracts admin team',
        nvpList_typeContractTemplate: 'e262634a-46c8-48c8-b39d-f288d24af871',
        nvpList_typeCategory: 'Production office'
      },
      {
        sys_nodedbid: '',
        nvpList_typeName: 'Director',
        nvpList_typeDescription: 'Direct the filming on a day to day basis',
        nvpList_typeDeliverableType: 'SERVICE',
        nvpList_typeChargeCode: '1010',
        nvpList_typePAYEStatus: 'PAYE',
        nvpList_typeWorkingWeek: 'Six (6) days per week',
        nvpList_typeBudgetMin: 250,
        nvpList_typeBudgetMax: 260,
        nvpList_typeHolidayPaidRate: 250,
        nvpList_typeOvertimePaidRate: 0,
        nvpList_typeNoticePeriod: 0,
        nvpList_typePaymentPeriod: 'Weekly',
        nvpList_typeRatePeriod: 'per day',
        nvpList_typeCurrency: 'GBP',
        nvpList_typeProcessName: 'Contract management process',
        nvpList_typeAdministrationTeam: 'Contracts admin team',
        nvpList_typeContractTemplate: 'e262634a-46c8-48c8-b39d-f288d24af871',
        nvpList_typeCategory: 'Production office'
      },
      {
        sys_nodedbid: '',
        nvpList_typeName: 'Assistant producer',
        nvpList_typeDescription: 'Manage the production and ensure delivery on time and to budget',
        nvpList_typeDeliverableType: 'SERVICE',
        nvpList_typeChargeCode: '1010',
        nvpList_typePAYEStatus: 'PAYE',
        nvpList_typeWorkingWeek: 'Six (6) days per week',
        nvpList_typeBudgetMin: 200,
        nvpList_typeBudgetMax: 220,
        nvpList_typeHolidayPaidRate: 200,
        nvpList_typeOvertimePaidRate: 0,
        nvpList_typeNoticePeriod: 0,
        nvpList_typePaymentPeriod: 'Weekly',
        nvpList_typeRatePeriod: 'per day',
        nvpList_typeCurrency: 'GBP',
        nvpList_typeProcessName: 'Contract management process',
        nvpList_typeAdministrationTeam: 'Contracts admin team',
        nvpList_typeContractTemplate: 'e262634a-46c8-48c8-b39d-f288d24af871',
        nvpList_typeCategory: 'Production office'
      },
      {
        sys_nodedbid: '',
        nvpList_typeName: 'Assistant director',
        nvpList_typeDescription: 'Manage the production and ensure delivery on time and to budget',
        nvpList_typeDeliverableType: 'SERVICE',
        nvpList_typeChargeCode: '1010',
        nvpList_typePAYEStatus: 'PAYE',
        nvpList_typeWorkingWeek: 'Six (6) days per week',
        nvpList_typeBudgetMin: 200,
        nvpList_typeBudgetMax: 220,
        nvpList_typeHolidayPaidRate: 200,
        nvpList_typeOvertimePaidRate: 0,
        nvpList_typeNoticePeriod: 0,
        nvpList_typePaymentPeriod: 'Weekly',
        nvpList_typeRatePeriod: 'per day',
        nvpList_typeCurrency: 'GBP',
        nvpList_typeProcessName: 'Contract management process',
        nvpList_typeAdministrationTeam: 'Contracts admin team',
        nvpList_typeContractTemplate: 'e262634a-46c8-48c8-b39d-f288d24af871',
        nvpList_typeCategory: 'Production office'
      },
      {
        sys_nodedbid: '',
        nvpList_typeName: 'Assistand director',
        nvpList_typeDescription: 'Manage the production and ensure delivery on time and to budget',
        nvpList_typeDeliverableType: 'SERVICE',
        nvpList_typeChargeCode: '1010',
        nvpList_typePAYEStatus: 'PAYE',
        nvpList_typeWorkingWeek: 'Six (6) days per week',
        nvpList_typeBudgetMin: 200,
        nvpList_typeBudgetMax: 220,
        nvpList_typeHolidayPaidRate: 200,
        nvpList_typeOvertimePaidRate: 0,
        nvpList_typeNoticePeriod: 0,
        nvpList_typePaymentPeriod: 'Weekly',
        nvpList_typeRatePeriod: 'per day',
        nvpList_typeCurrency: 'GBP',
        nvpList_typeProcessName: 'Contract management process',
        nvpList_typeAdministrationTeam: 'Contracts admin team',
        nvpList_typeContractTemplate: 'e262634a-46c8-48c8-b39d-f288d24af871',
        nvpList_typeCategory: 'Production office'
      },
      {
        sys_nodedbid: '',
        nvpList_typeName: 'Finance manager',
        nvpList_typeDescription: 'Manage the financial aspects of the production to budget',
        nvpList_typeDeliverableType: 'SERVICE',
        nvpList_typeChargeCode: '1010',
        nvpList_typePAYEStatus: 'PAYE',
        nvpList_typeWorkingWeek: 'Six (6) days per week',
        nvpList_typeBudgetMin: 280,
        nvpList_typeBudgetMax: 320,
        nvpList_typeHolidayPaidRate: 280,
        nvpList_typeOvertimePaidRate: 0,
        nvpList_typeNoticePeriod: 0,
        nvpList_typePaymentPeriod: 'Weekly',
        nvpList_typeRatePeriod: 'per day',
        nvpList_typeCurrency: 'GBP',
        nvpList_typeProcessName: 'Contract management process',
        nvpList_typeAdministrationTeam: 'Contracts admin team',
        nvpList_typeContractTemplate: 'e262634a-46c8-48c8-b39d-f288d24af871',
        nvpList_typeCategory: 'Production office'
      },
      {
        sys_nodedbid: '',
        nvpList_typeName: 'FInancial assistant',
        nvpList_typeDescription: 'Manage the production and ensure delivery on time and to budget',
        nvpList_typeDeliverableType: 'SERVICE',
        nvpList_typeChargeCode: '1010',
        nvpList_typePAYEStatus: 'PAYE',
        nvpList_typeWorkingWeek: 'Six (6) days per week',
        nvpList_typeBudgetMin: 240,
        nvpList_typeBudgetMax: 250,
        nvpList_typeHolidayPaidRate: 250,
        nvpList_typeOvertimePaidRate: 0,
        nvpList_typeNoticePeriod: 0,
        nvpList_typePaymentPeriod: 'Weekly',
        nvpList_typeRatePeriod: 'per day',
        nvpList_typeCurrency: 'GBP',
        nvpList_typeProcessName: 'Contract management process',
        nvpList_typeAdministrationTeam: 'Contracts admin team',
        nvpList_typeContractTemplate: 'e262634a-46c8-48c8-b39d-f288d24af871',
        nvpList_typeCategory: 'Production office'
      },

      /** back stage */
      {
        sys_nodedbid: '',
        nvpList_typeName: 'Wardrobe Manager',
        nvpList_typeDescription: 'Manage the costumes',
        nvpList_typeDeliverableType: 'SERVICE',
        nvpList_typeChargeCode: '1010',
        nvpList_typePAYEStatus: 'PAYE',
        nvpList_typeWorkingWeek: 'Six (6) days per week',
        nvpList_typeBudgetMin: 200,
        nvpList_typeBudgetMax: 220,
        nvpList_typeHolidayPaidRate: 200,
        nvpList_typeOvertimePaidRate: 0,
        nvpList_typeNoticePeriod: 0,
        nvpList_typePaymentPeriod: 'Weekly',
        nvpList_typeRatePeriod: 'per day',
        nvpList_typeCurrency: 'GBP',
        nvpList_typeProcessName: 'Contract management process',
        nvpList_typeAdministrationTeam: 'Contracts admin team',
        nvpList_typeContractTemplate: 'e262634a-46c8-48c8-b39d-f288d24af871',
        nvpList_typeCategory: 'Back stage'
      },
      {
        sys_nodedbid: '',
        nvpList_typeName: 'Wardrobe assistant',
        nvpList_typeDescription: 'Assist the wardrobe manager',
        nvpList_typeDeliverableType: 'SERVICE',
        nvpList_typeChargeCode: '1010',
        nvpList_typePAYEStatus: 'PAYE',
        nvpList_typeWorkingWeek: 'Six (6) days per week',
        nvpList_typeBudgetMin: 200,
        nvpList_typeBudgetMax: 220,
        nvpList_typeHolidayPaidRate: 200,
        nvpList_typeOvertimePaidRate: 0,
        nvpList_typeNoticePeriod: 0,
        nvpList_typePaymentPeriod: 'Weekly',
        nvpList_typeRatePeriod: 'per day',
        nvpList_typeCurrency: 'GBP',
        nvpList_typeProcessName: 'Contract management process',
        nvpList_typeAdministrationTeam: 'Contracts admin team',
        nvpList_typeContractTemplate: 'e262634a-46c8-48c8-b39d-f288d24af871',
        nvpList_typeCategory: 'Back stage'
      },
      {
        sys_nodedbid: '',
        nvpList_typeName: 'Stage manager',
        nvpList_typeDescription: 'Be a stage manager',
        nvpList_typeDeliverableType: 'SERVICE',
        nvpList_typeChargeCode: '1010',
        nvpList_typePAYEStatus: 'PAYE',
        nvpList_typeWorkingWeek: 'Six (6) days per week',
        nvpList_typeBudgetMin: 200,
        nvpList_typeBudgetMax: 220,
        nvpList_typeHolidayPaidRate: 200,
        nvpList_typeOvertimePaidRate: 0,
        nvpList_typeNoticePeriod: 0,
        nvpList_typePaymentPeriod: 'Weekly',
        nvpList_typeRatePeriod: 'per day',
        nvpList_typeCurrency: 'GBP',
        nvpList_typeProcessName: 'Contract management process',
        nvpList_typeAdministrationTeam: 'Contracts admin team',
        nvpList_typeContractTemplate: 'e262634a-46c8-48c8-b39d-f288d24af871',
        nvpList_typeCategory: 'Back stage'
      },
      {
        sys_nodedbid: '',
        nvpList_typeName: 'Set builder',
        nvpList_typeDescription: 'Build the sets',
        nvpList_typeDeliverableType: 'SERVICE',
        nvpList_typeChargeCode: '1010',
        nvpList_typePAYEStatus: 'PAYE',
        nvpList_typeWorkingWeek: 'Six (6) days per week',
        nvpList_typeBudgetMin: 200,
        nvpList_typeBudgetMax: 220,
        nvpList_typeHolidayPaidRate: 200,
        nvpList_typeOvertimePaidRate: 0,
        nvpList_typeNoticePeriod: 0,
        nvpList_typePaymentPeriod: 'Weekly',
        nvpList_typeRatePeriod: 'per day',
        nvpList_typeCurrency: 'GBP',
        nvpList_typeProcessName: 'Contract management process',
        nvpList_typeAdministrationTeam: 'Contracts admin team',
        nvpList_typeContractTemplate: 'e262634a-46c8-48c8-b39d-f288d24af871',
        nvpList_typeCategory: 'Back stage'
      },
      {
        sys_nodedbid: '',
        nvpList_typeName: 'Electrician',
        nvpList_typeDescription: 'Change the fuses',
        nvpList_typeDeliverableType: 'SERVICE',
        nvpList_typeChargeCode: '1010',
        nvpList_typePAYEStatus: 'PAYE',
        nvpList_typeWorkingWeek: 'Six (6) days per week',
        nvpList_typeBudgetMin: 200,
        nvpList_typeBudgetMax: 220,
        nvpList_typeHolidayPaidRate: 200,
        nvpList_typeOvertimePaidRate: 0,
        nvpList_typeNoticePeriod: 0,
        nvpList_typePaymentPeriod: 'Weekly',
        nvpList_typeRatePeriod: 'per day',
        nvpList_typeCurrency: 'GBP',
        nvpList_typeProcessName: 'Contract management process',
        nvpList_typeAdministrationTeam: 'Contracts admin team',
        nvpList_typeContractTemplate: 'e262634a-46c8-48c8-b39d-f288d24af871',
        nvpList_typeCategory: 'Back stage'
      },
      {
        sys_nodedbid: '',
        nvpList_typeName: 'Rigger',
        nvpList_typeDescription: 'Rig the stage',
        nvpList_typeDeliverableType: 'SERVICE',
        nvpList_typeChargeCode: '1010',
        nvpList_typePAYEStatus: 'PAYE',
        nvpList_typeWorkingWeek: 'Six (6) days per week',
        nvpList_typeBudgetMin: 200,
        nvpList_typeBudgetMax: 220,
        nvpList_typeHolidayPaidRate: 200,
        nvpList_typeOvertimePaidRate: 0,
        nvpList_typeNoticePeriod: 0,
        nvpList_typePaymentPeriod: 'Weekly',
        nvpList_typeRatePeriod: 'per day',
        nvpList_typeCurrency: 'GBP',
        nvpList_typeProcessName: 'Contract management process',
        nvpList_typeAdministrationTeam: 'Contracts admin team',
        nvpList_typeContractTemplate: 'e262634a-46c8-48c8-b39d-f288d24af871',
        nvpList_typeCategory: 'Back stage'
      },

      /** film crew */
      {
        sys_nodedbid: '',
        nvpList_typeName: 'Cameraman',
        nvpList_typeDescription: 'Take photos',
        nvpList_typeDeliverableType: 'SERVICE',
        nvpList_typeChargeCode: '1010',
        nvpList_typePAYEStatus: 'PAYE',
        nvpList_typeWorkingWeek: 'Six (6) days per week',
        nvpList_typeBudgetMin: 240,
        nvpList_typeBudgetMax: 260,
        nvpList_typeHolidayPaidRate: 240,
        nvpList_typeOvertimePaidRate: 0,
        nvpList_typeNoticePeriod: 0,
        nvpList_typePaymentPeriod: 'Weekly',
        nvpList_typeRatePeriod: 'per day',
        nvpList_typeCurrency: 'GBP',
        nvpList_typeProcessName: 'Contract management process',
        nvpList_typeAdministrationTeam: 'Contracts admin team',
        nvpList_typeContractTemplate: 'e262634a-46c8-48c8-b39d-f288d24af871',
        nvpList_typeCategory: 'Film crew'
      },
      {
        sys_nodedbid: '',
        nvpList_typeName: 'Assistant cameraman',
        nvpList_typeDescription: 'Manage the production and ensure delivery on time and to budget',
        nvpList_typeDeliverableType: 'SERVICE',
        nvpList_typeChargeCode: '1010',
        nvpList_typePAYEStatus: 'PAYE',
        nvpList_typeWorkingWeek: 'Six (6) days per week',
        nvpList_typeBudgetMin: 220,
        nvpList_typeBudgetMax: 230,
        nvpList_typeHolidayPaidRate: 220,
        nvpList_typeOvertimePaidRate: 0,
        nvpList_typeNoticePeriod: 0,
        nvpList_typePaymentPeriod: 'Weekly',
        nvpList_typeRatePeriod: 'per day',
        nvpList_typeCurrency: 'GBP',
        nvpList_typeProcessName: 'Contract management process',
        nvpList_typeAdministrationTeam: 'Contracts admin team',
        nvpList_typeContractTemplate: 'e262634a-46c8-48c8-b39d-f288d24af871',
        nvpList_typeCategory: 'Film crew'
      },

      /** writing team */
      {
        sys_nodedbid: '',
        nvpList_typeName: 'Writer',
        nvpList_typeDescription: 'Write the script',
        nvpList_typeDeliverableType: 'SERVICE',
        nvpList_typeChargeCode: '1010',
        nvpList_typePAYEStatus: 'PAYE',
        nvpList_typeWorkingWeek: 'Six (6) days per week',
        nvpList_typeBudgetMin: 200,
        nvpList_typeBudgetMax: 220,
        nvpList_typeHolidayPaidRate: 200,
        nvpList_typeOvertimePaidRate: 0,
        nvpList_typeNoticePeriod: 0,
        nvpList_typePaymentPeriod: 'Weekly',
        nvpList_typeRatePeriod: 'per day',
        nvpList_typeCurrency: 'GBP',
        nvpList_typeProcessName: 'Contract management process',
        nvpList_typeAdministrationTeam: 'Contracts admin team',
        nvpList_typeContractTemplate: 'e262634a-46c8-48c8-b39d-f288d24af871',
        nvpList_typeCategory: 'Writing team'
      },
      {
        sys_nodedbid: '',
        nvpList_typeName: 'Assistant writer',
        nvpList_typeDescription: 'Check the spelling of the writer',
        nvpList_typeDeliverableType: 'SERVICE',
        nvpList_typeChargeCode: '1010',
        nvpList_typePAYEStatus: 'PAYE',
        nvpList_typeWorkingWeek: 'Six (6) days per week',
        nvpList_typeBudgetMin: 150,
        nvpList_typeBudgetMax: 180,
        nvpList_typeHolidayPaidRate: 150,
        nvpList_typeOvertimePaidRate: 0,
        nvpList_typeNoticePeriod: 0,
        nvpList_typePaymentPeriod: 'Weekly',
        nvpList_typeRatePeriod: 'per day',
        nvpList_typeCurrency: 'GBP',
        nvpList_typeProcessName: 'Contract management process',
        nvpList_typeAdministrationTeam: 'Contracts admin team',
        nvpList_typeContractTemplate: 'e262634a-46c8-48c8-b39d-f288d24af871',
        nvpList_typeCategory: 'Writing team'
      }
    ]
  };

  constructor() {

    this.lists.push(this.mediaBronze);

  }

  public getLists(): Observable<ProductDefaultRoleList[]> {

    return Observable.of(this.lists);

  }


}

